name: Build & Test

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: gcc:16 
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Compiler 
        run: ln -s /usr/local/bin/gcc /usr/local/bin/gcc-16

      - name: Build
        run: make 

      - name: Run Tests
        run: make test